export type LangType = 'vi' | 'en';

export const translations = {
  vi: {
    // LockScreen / Setup
    app_title: 'Ví Mật Mã',
    lock_setupState: 'Thiết lập Kho bảo mật',
    lock_decryptState: 'Giải mã Kho lưu trữ',
    lock_setupSubtext: 'Mã hóa thông tin cá nhân của bạn trực triếp trên trình duyệt',
    lock_decryptSubtext: 'Nhập mật khẩu Master để truy cập các mật khẩu đã được mã hóa của bạn',
    lock_masterPwdLabel: 'Mật khẩu Master mới',
    lock_masterConfirmLabel: 'Xác nhận Mật khẩu Master',
    lock_initButton: 'Khởi tạo Kho mật khẩu',
    lock_decryptLoading: 'Đang giải mã dữ liệu...',
    lock_setupLoading: 'Đang tạo khóa mã hóa...',
    lock_loginButton: 'Giải mã và Đăng nhập',
    lock_incorrectPwd: 'Mật khẩu Master không đúng hoặc định dạng sai.',
    lock_genericError: 'Nhập sai mật khẩu Master hoặc dữ liệu lưu trữ đã bị thay đổi.',
    lock_resetWarning: 'CẢNH BÁO: Hành động này sẽ XÓA TOÀN BỘ dữ liệu mật khẩu hiện có trong thiết bị và bắt đầu lại kho mới. Khôi phục lại là KHÔNG thể trừ khi bạn có tệp sao lưu. Bạn có chắc chắn muốn tiếp tục?',
    lock_resetLink: 'Xóa sạch kho dữ liệu & tạo lại Master Password',
    lock_aesgcmText: 'Mã hóa bảo mật cao 256-bit AES-GCM cục bộ. Dữ liệu của bạn được an toàn tuyệt đối.',
    lock_enterMinText: 'Nhập tối thiểu 8 ký tự...',
    lock_enterPwdPlc: 'Nhập mật khẩu Master...',
    lock_enterConfirmPlc: 'Nhập lại mật khẩu Master...',
    lock_warningTitle: 'Lưu ý quan trọng:',
    lock_warningText: 'Mật khẩu này không thể khôi phục hay đổi lại nếu bạn quên. Tất cả dữ liệu của bạn được mã hóa an toàn offline. Hãy lưu mật khẩu Master ở nơi thích hợp.',
    lock_enterMasterAlert: 'Vui lòng nhập mật khẩu Master.',
    lock_masterMinError: 'Mật khẩu Master phải dài ít nhất 8 ký tự.',
    lock_masterMatchError: 'Mật khẩu xác nhận không trùng khớp.',
    lock_failSetupSystem: 'Không thể thiết lập mật khẩu Master. Đã xảy ra lỗi hệ thống.',
    lock_failDbNotFound: 'Không tìm thấy dữ liệu kho khóa.',

    // Header Controls
    head_createPwd: 'Tạo mật khẩu',
    head_backup: 'Sao lưu lưu trữ',
    head_encryptionText: 'Mã hóa AES-256 nội bộ',
    head_renameBtn: 'Gợi ý & Thay đổi tên ứng dụng',
    head_autolock: 'Tự khóa:',
    head_min: 'phút',
    head_sec: 'giây',
    head_lockBtn: 'Khóa kho ngay lập tức',
    head_toastUnlocked: 'Đã mở khóa thành công! Chào mừng trở lại.',
    head_toastLocked: 'Đã khóa kho dữ liệu an toàn.',
    head_toastAutoLock: 'Kho đã tự động khóa do bạn không hoạt động.',
    head_toastChangeTime: 'Đã đổi thời gian tự khóa kho:',
    head_toastBackupDownloaded: 'Tải xuống tệp sao lưu thành công!',
    head_toastBackupError: 'Không thể tải tệp sao lưu.',
    head_toastRestoreSuccess: 'Khôi phục hoàn tất! Khóa lại để xác minh.',
    head_toastRestoreError: 'Định dạng tệp sao lưu không đúng chuẩn mã hóa.',
    head_toastFileError: 'Tệp sao lưu bị lỗi hoặc sai định dạng.',
    head_toastAddSuccess: 'Đã lưu tài khoản bảo mật mới!',
    head_toastEditSuccess: 'Cập nhật tài khoản thành công!',
    head_toastDeleteSuccess: 'Đã xóa vĩnh viễn dữ liệu.',
    head_toastMoveCategory: 'Đã di chuyển loại lưu trữ!',
    head_renameSuggestionsTitle: 'Gợi ý tên ứng dụng',
    head_renameDesc: 'Chọn một cái tên chuyên nghiệp hoặc tự đặt theo ý muốn:',
    head_renameCustomField: 'Đặt tên tùy chỉnh',
    head_renameCustomPlc: 'Đặt tên riêng...',
    head_renameSave: 'Lưu',

    // Reminders
    rem_title: 'Sự kiện sắp tới',
    rem_desc: '',
    rem_today: 'Hôm nay ⭐',
    rem_daysLeft: 'Còn {n} ngày',
    rem_daysPassed: 'Đã qua {n} ngày',
    rem_quickView: 'Xem nhanh →',
    rem_yearly: 'Hàng năm 🎂',
    rem_monthly: 'Hàng tháng 📅',
    rem_once: 'Một lần 📌',

    // Sidebar
    side_addNewBtn: 'Thêm tài khoản mới',
    side_addNewAccount: 'Thêm tài khoản mật khẩu',
    side_quickFilters: 'Bộ lọc nhanh',
    side_allAccounts: 'Tất cả mật hiệu',
    side_starred: 'Đã đánh dấu sao',
    side_storageTypes: 'Danh mục kho khóa',
    side_displayBtn: 'Hiển thị',
    side_unlockEditTooltip: 'Mở khóa để thay đổi vị trí, sửa/đổi tên danh mục tùy thích',
    side_lockEditTooltip: 'Khóa chế độ biên tập',
    side_lockedState: 'Khóa sửa',
    side_editState: 'Biên tập',
    side_filterHeader: 'LỰA CHỌN PHÂN LOẠI',
    side_all: 'Tất cả tài khoản',
    side_favorites: 'Yêu thích',
    side_customAddTip: 'Tên loại lưu trữ mới',
    side_customAddPlc: 'Bấm Enter để thêm...',
    side_customDuplicateError: 'Tên loại lưu trữ này đã tồn tại!',
    side_customRenamePrompt: 'Nhập tên mới cho loại lưu trữ',
    side_customDeleteDeny: 'Không thể xóa do đang chứa tài khoản!',
    side_customDeleteSuccess: 'Đã xóa loại lưu trữ',
    side_customRenameSuccess: 'Đã thay đổi tên loại thành',
    side_hideEmpty: 'Ẩn danh mục trống',
    side_showEmpty: 'Hiện danh mục trống',
    side_hideCounts: 'Ẩn số lượng mật khẩu',
    side_showCounts: 'Hiện số lượng',
    side_compactMode: 'Chế độ xem gọn danh mục',
    side_defaultMode: 'Chế độ danh sách rộng',
    side_sortAlpha: 'Sắp xếp: Tên A-Z',
    side_sortCount: 'Sắp xếp: Số lượng mật khẩu',
    side_sortDefault: 'Sắp xếp: Thứ tự tùy thích',
    side_optCompact: 'Chế độ xem gọn danh mục',
    side_optHideEmpty: 'Ẩn các mục chưa có mật khẩu',
    side_optHideCounts: 'Ẩn số lượng đếm bản ghi',
    side_optHideSums: 'Ẩn tóm tắt nhanh nội dung',
    side_sortHeading: 'Chế độ sắp xếp',
    side_sortManual: 'Tùy chọn',
    side_layoutHeading: 'Bố cục chuyên mục',
    side_layoutList: 'Danh sách',
    side_layoutGrid: 'Ô lưới',
    side_moveUp: 'Di chuyển lên đầu',
    side_moveDown: 'Di chuyển xuống dưới',
    side_renameCatTooltip: 'Đổi tên chuyên mục này',
    side_deleteCatTooltip: 'Xóa vĩnh viễn chuyên mục này',
    side_addNewCatBtn: 'Tạo chuyên mục mới',
    side_newCatHeader: 'Thiết lập loại chuyên mục',
    side_newCatLabelField: 'Tên chuyên mục hiển thị',
    side_newCatLabelPlc: 'Ví dụ: Tài khoản Facebook, Ngân hàng thứ hai...',
    side_newCatSchemaField: 'Kiểu giao diện biểu mẫu mẫu',
    side_adviceHeader: 'Nguyên lý bảo mật',
    side_advicePara1: 'Trình quản lý tệp mật khẩu an toàn chạy độc lập hoàn toàn trên điện thoại hoặc trình duyệt của bạn (Offline-First).',
    side_advicePara2: 'Tất cả các cơ sở dữ liệu đều được lưu trữ trực tiếp dưới dạng băm AES-256 an toàn.',

    // Main Workspace list
    main_searchPlc: 'Tìm kiếm theo từ khóa...',
    main_compactSummaryMode: 'Chế độ xem nhanh thu gọn',
    main_sortRecent: 'Sắp xếp: Mới cập nhật',
    main_sortAlpha: 'Sắp xếp: Tên A-Z',
    main_noDataFound: 'Không tìm thấy dữ liệu khớp từ khóa.',
    main_noDataInCategory: 'Không có tài khoản nào được lưu ở mục này.',
    main_deleteConfirm: 'Bạn chắc chắn muốn xóa vĩnh viễn dữ liệu này?',
    work_searchPlaceholder: 'Tìm kiếm nhanh mật khẩu, tài khoản, ghi chú hoặc trang tính...',
    work_sortByLabel: 'Sắp xếp:',
    work_sortByRecent: 'Gần đây',
    work_sortByAlpha: 'Tên A-Z',
    work_viewModeLabel: 'Chế độ xem:',
    work_viewGridTooltip: 'Hiển thị dạng thẻ lưới (Bento Grid)',
    work_viewTableTooltip: 'Hiển thị dạng dòng bảng danh sách',

    // Category dynamic labels
    cat_bank: 'Tài khoản Ngân hàng',
    cat_social: 'Mạng xã hội',
    cat_web: 'Tài khoản Web / App',
    cat_wallet: 'Ví Crypto (Binance...)',
    cat_ewallet: 'Ví điện tử Momo/Zalo',
    cat_phoneapp: 'Ứng dụng di động',
    cat_sheet: 'Google Trang tính',
    cat_note: 'Ghi chú / Mật hiệu',

    // Bank Account fields
    f_bankName: 'Tên Ngân hàng',
    f_accountNumber: 'Số tài khoản',
    f_accountHolder: 'Chủ tài khoản',
    f_pin: 'Mã PIN bảo mật',
    f_username: 'Tài khoản đăng nhập',
    f_password: 'Mật khẩu giao dịch',
    f_branch: 'Chi nhánh mở thẻ',
    f_notes: 'Ghi chú bổ sung',
    f_title: 'Tiêu đề lưu trữ',

    // Social fields
    f_platformName: 'Tên nền tảng',

    // Web fields
    f_websiteUrl: 'Địa chỉ Website',

    // Crypto Wallet
    f_walletName: 'Tên ví Crypto',
    f_walletType: 'Phân loại ví',
    f_walletAddress: 'Địa chỉ ví công khai',
    f_recoverySeed: 'Mã phục hồi Seedphrase (12-24 từ)',
    f_privateKey: 'Khóa cá nhân Private Key',
    f_wallet_type_exchange: 'Sàn giao dịch tập trung',
    f_wallet_type_dex: 'Ví Non-custodial / App',
    f_wallet_type_hw: 'Ví lạnh / ví cứng',

    // EWallet fields
    f_ewalletName: 'Tên ví điện tử',
    f_phoneNumber: 'Số điện thoại',
    f_linkedBank: 'Ngân hàng liên kết',

    // Phoneapp fields
    f_appName: 'Tên ứng dụng di động',
    f_nationalId: 'Số căn cước công dân CCCD',
    f_passcode: 'Mã Pin / Passcode',

    // Google sheet
    f_sheetColumns: 'Số cột tiêu đề',
    f_sheetRows: 'Số dòng dữ liệu',
    f_integratedGSheet: 'Google Sheet đồng bộ hóa',
    f_privateSync: 'Quyền riêng tư',
    f_syncTime: 'Thời điểm đồng bộ',

    // Secure Note fields
    f_notesContent: 'Nội dung ghi chú mật',

    // Reminder Config
    r_reminderEnabled: 'Bật thông báo sự kiện',
    r_reminderType: 'Phương thức nhắc',
    r_reminderDate: 'Ngày diễn ra',
    r_reminderMsg: 'Thông điệp nhắc nhở',
    r_once: 'Một lần duy nhất',
    r_yearly: 'Nhắc lại hàng năm (sinh nhật/kỷ niệm)',

    // Actions
    a_edit: 'Chỉnh sửa',
    a_delete: 'Xóa bỏ',
    a_save: 'Lưu thay đổi',
    a_cancel: 'Hủy bỏ',
    a_copied: 'Đã sao chép!',
    a_copy: 'Sao chép',
    a_addNew: 'Thêm mới',
    a_search: 'Tìm kiếm',
    a_show: 'Xem',
    a_hide: 'Ẩn',
    a_sync: 'Đồng bộ',
    a_favoriteHint: 'Đặt làm yêu thích',
    a_settings: 'Cấu hình hệ thống',
    a_export_backup: 'Tải file sao lưu (JSON)',
    a_import_backup: 'Khôi phục từ file backup',
    a_import_choose: 'Chọn tệp backup...',
    a_import_success: 'Nhập dữ liệu thành công!',
    a_generate_pwd: 'Tạo mật khẩu ngẫu nhiên cho bạn',
    a_open_workspace: 'Mở không gian làm việc rộng',
    a_workspace_title: 'Không gian làm việc bảng tính an toàn',

    // Settings Panel
    sett_title: 'Quản lý sao lưu & khôi phục dữ liệu',
    sett_desc: 'Toàn bộ thông tin được mã hóa an toàn offline ngay trên bộ nhớ trình duyệt của bạn (localStorage). Tải file sao lưu (JSON) thường xuyên để tránh mất dữ liệu khi xóa lịch sử web.',
    sett_exportHeader: 'Xuất dữ liệu an toàn',
    sett_exportDesc: 'Xuất toàn bộ cơ sở dữ liệu đã mã hóa thành một tệp tin JSON an toàn để lưu trữ riêng tư.',
    sett_exportBtn: 'Tải xuống dữ liệu mã hóa (.json)',
    sett_importHeader: 'Nhập & khôi phục dữ liệu',
    sett_importWarningLabel: 'Cảnh báo',
    sett_importWarningDesc: 'Dữ liệu mới tải lên sẽ thay thế hoàn toàn kho mật khẩu hiện tại trên thiết bị này.',
    sett_importBtn: 'Chọn tệp sao lưu để nhập dữ liệu',

    // Theme selector
    theme_title: 'Chủ đề giao diện cao cấp',
    theme_desc: 'Cá nhân hóa két mật mã với màu sắc hiển thị khác nhau. Tính năng cao cấp dành riêng cho gói PRO.',
    theme_slate: 'Slate Cận Vệ',
    theme_cyberpunk: 'Cyberpunk Neon',
    theme_emerald: 'Emerald Classic',
    theme_darkspace: 'Dark Space',
    theme_unlocked_toast: 'Đã áp dụng chủ đề màu sắc mới thành công!',
    theme_locked_toast: 'Chủ đề màu sắc cao cấp yêu cầu kích hoạt PRO Cận Vệ!',

    // Empty States
    work_emptyTitle: 'Kho của bạn hiện đang trống',
    work_emptySearch: 'Không tìm thấy tài khoản nào khớp với từ khóa tìm kiếm của bạn. Hãy thử từ khóa khác.',
    work_emptyDesc: 'Không có tài khoản hoặc tài liệu bảo mật nào được lưu trong thư mục này.',
    work_createFirst: 'Khởi tạo tài khoản mật khẩu đầu tiên',

    // Free vs Pro & Security Audit
    tier_free: 'Bản Miễn Phí',
    tier_pro: 'Bản PRO Cận Vệ',
    tier_upgradeBtn: 'Kích hoạt PRO ngay',
    tier_proActive: 'Đã kích hoạt PRO Elite',
    tier_proBanner: 'Mở khóa toàn bộ tính năng và Đánh giá An toàn Mật khẩu nâng cao.',
    tier_upgradeTitle: 'Nâng cấp lên Ví Mật Mã PRO',
    tier_compareTitle: 'So sánh các tính năng bảo mật',
    tier_feature_desc1: 'Lưu trữ mật khẩu không giới hạn thiết bị',
    tier_feature_desc2: 'Mã hóa quân đội AES-GCM 256-bit ngoại tuyến',
    tier_feature_desc3: 'Trình tạo mã 2FA / TOTP Authenticator tích hợp',
    tier_feature_desc4: 'Trung tâm đánh giá sức khỏe & Cảnh báo rò rỉ mật khẩu',
    tier_feature_desc5: 'Đồng bộ đám mây và Auto-Backup với Google Sheets',
    tier_feature_desc6: 'Chế độ bảo vệ nghiêm ngặt & Tự bảo mật cấp cao nhất',
    tier_enterCode: 'Nhập Mã kích hoạt hoặc Voucher PRO',
    tier_codePlc: 'Nhập mã VIP2026 hoặc nhấn Kích hoạt miễn phí...',
    tier_invalidCode: 'Mã kích hoạt không đúng hoặc đã hết hạn!',
    tier_successUpgrade: 'Chúc mừng! Bạn đã nâng cấp thành công lên phiên bản PRO đặc biệt!',
    
    // TOTP fields
    totp_secretLabel: 'Khoá bí mật 2FA/TOTP (Base32)',
    totp_secretPlc: 'Nhập mã bí mật từ Google / Facebook... ví dụ: JBSWY3DPEHPK3PXP',
    totp_codeLabel: 'Mã xác thực 2 bước (2FA)',
    totp_desc: 'Tự động tạo mã xác minh 6 chữ số xoay vòng mỗi 30 giây.',
    totp_copied: 'Đã sao chép mã 2FA vào khay nhớ tạm!',
    launch_openNewTab: 'Mở ở tab mới',
    launch_openIncognito: 'Mở bằng tab ẩn danh (Copy & HD)',
    launch_openAndCopyPass: 'Mở & tự động copy mật khẩu',
    launch_copyLink: 'Sao chép liên kết',
    launch_incognitoToast: 'Đã copy link! Hãy nhấn Ctrl+Shift+N (Windows) hoặc Cmd+Shift+N (Mac) để mở ẩn danh và dán vào.',
    
    // Audit Dashboard
    audit_title: 'Kiểm toán & Đánh giá Sức khoẻ Mật khẩu',
    audit_score: 'Điểm An toàn Kho mật mã',
    audit_scoreDesc: 'Điểm càng cao nghĩa là các mật khẩu của bạn càng có độ phức tạp lớn, không trùng lặp và được kích hoạt 2FA đầy đủ.',
    audit_total: 'Tổng số tài khoản phân tích',
    audit_weak: 'Mật khẩu yếu, dễ bẻ khóa',
    audit_weakDesc: 'Mật khẩu có độ dài nhỏ hơn 8 ký tự hoặc chỉ chứa chữ hoặc số đơn thuần.',
    audit_reused: 'Mật khẩu trùng lặp',
    audit_reusedDesc: 'Bạn đang dùng chung một mật khẩu cho nhiều tài khoản khác nhau, tăng nguy cơ rò rỉ dây chuyền.',
    audit_no2fa: 'Chưa kích hoạt bảo mật 2FA',
    audit_no2faDesc: 'Tài khoản chưa lưu khóa TOTP. Hãy bật 2FA để bảo mật tuyệt đối.',
    audit_leaked: 'Rò rỉ & Nguy hiểm cao',
    audit_leakedDesc: 'Các mật khẩu nằm trong danh sách rò rỉ phổ biến hoặc cực kỳ dễ đoán (ví dụ: 123456, password, admin).',
    audit_perfect: 'Chúc mừng! Kho khóa của bạn cực kỳ an toàn, đạt điểm tuyệt đối.',
    audit_listWeak: 'Danh sách mật khẩu cần đổi mới gấp',
    audit_listReused: 'Mật khẩu dùng trùng lặp',
    audit_listNo2fa: 'Tài khoản nên bổ sung 2FA',
    audit_statusSafe: 'Rất an toàn',
    audit_statusWarning: 'Cần chú ý',
    audit_statusCritical: 'Khẩn cấp / Nguy hiểm',
  },
  en: {
    // LockScreen / Setup
    app_title: 'Save Code',
    lock_setupState: 'Set up Secure Vault',
    lock_decryptState: 'Decrypt Database',
    lock_setupSubtext: 'Encrypt your personal information natively inside your browser',
    lock_decryptSubtext: 'Enter Master Password to access your encrypted account information',
    lock_masterPwdLabel: 'New Master Password',
    lock_masterConfirmLabel: 'Confirm Master Password',
    lock_initButton: 'Initialize Secret Vault',
    lock_decryptLoading: 'Decrypting storage...',
    lock_setupLoading: 'Generating encryption key...',
    lock_loginButton: 'Decrypt & Login',
    lock_incorrectPwd: 'Master Password incorrect or database structure altered.',
    lock_genericError: 'Wrong Master Password or your storage data has been tampered.',
    lock_resetWarning: 'WARNING: This will PERMANENTLY ERASE all secure password data stored on this device! Make sure you have a JSON backup file. Are you sure you want to continue?',
    lock_resetLink: 'Erase all vault data & Re-setup Master Password',
    lock_aesgcmText: 'Local military-grade 256-bit AES-GCM encryption. Your data is absolute private.',
    lock_enterMinText: 'Minimum 8 characters...',
    lock_enterPwdPlc: 'Enter Master Password...',
    lock_enterConfirmPlc: 'Re-enter Master Password...',
    lock_warningTitle: 'Important Safety Notice:',
    lock_warningText: 'This Master Password can NOT be recovered or updated if lost. All your codes are strictly offline. Keep the Master Password safe.',
    lock_enterMasterAlert: 'Please type the Master Password first.',
    lock_masterMinError: 'Master Password must consist of at least 8 characters.',
    lock_masterMatchError: 'The confirmation password does not match.',
    lock_failSetupSystem: 'Could not write Master Password due to system exceptions.',
    lock_failDbNotFound: 'Encryption Database was not found.',

    // Header Controls
    head_createPwd: 'Password Gen',
    head_backup: 'Backup Storage',
    head_encryptionText: 'Local AES-256 Storage',
    head_renameBtn: 'Rename Vault Title',
    head_autolock: 'Auto Lock:',
    head_min: 'min',
    head_sec: 'sec',
    head_lockBtn: 'Lock database instantly',
    head_toastUnlocked: 'Successfully unlocked! Welcome back.',
    head_toastLocked: 'Secure vault locked in memory.',
    head_toastAutoLock: 'Vault was automatically locked due to inactivity.',
    head_toastChangeTime: 'Auto-lock timer updated to:',
    head_toastBackupDownloaded: 'Encrypted backup downloaded successfully!',
    head_toastBackupError: 'Could not compile backup file.',
    head_toastRestoreSuccess: 'Imported successfully! Re-lock to verify keys.',
    head_toastRestoreError: 'Backup file is not matching proper encrypted schema.',
    head_toastFileError: 'Malformed backup file format.',
    head_toastAddSuccess: 'Successfully added new credential!',
    head_toastEditSuccess: 'Successfully updated credential details!',
    head_toastDeleteSuccess: 'Credential deleted permanently.',
    head_toastMoveCategory: 'Dynamic sort indices updated!',
    head_renameSuggestionsTitle: 'Select Display Identity',
    head_renameDesc: 'Pick a clean identifier title or input a custom name:',
    head_renameCustomField: 'Custom App Identity',
    head_renameCustomPlc: 'My Secret Locker...',
    head_renameSave: 'Apply',

    // Reminders
    rem_title: 'Upcoming Events',
    rem_desc: '',
    rem_today: 'Today ⭐',
    rem_daysLeft: '{n} days left',
    rem_daysPassed: '{n} days passed',
    rem_quickView: 'Locate item →',
    rem_yearly: 'Annually 🎂',
    rem_monthly: 'Monthly 📅',
    rem_once: 'One-time 📌',

    // Sidebar
    side_addNewBtn: 'Add Core Credential',
    side_addNewAccount: 'Add Secure Credential',
    side_quickFilters: 'Quick Filter Presets',
    side_allAccounts: 'All Credentials',
    side_starred: 'Starred Safe',
    side_storageTypes: 'Category Locker',
    side_displayBtn: 'Display',
    side_unlockEditTooltip: 'Unlock to customize category sort hierarchies and rename categories',
    side_lockEditTooltip: 'Lock customize edits mode',
    side_lockedState: 'Locked',
    side_editState: 'Bi-editing',
    side_filterHeader: 'CATEGORIES & FILTERS',
    side_all: 'All Safe Credentials',
    side_favorites: 'Starred Vaults',
    side_customAddTip: 'New category label',
    side_customAddPlc: 'Press Enter to create...',
    side_customDuplicateError: 'This category title already exists!',
    side_customRenamePrompt: 'Modify category display label',
    side_customDeleteDeny: 'Cannot delete nonempty category!',
    side_customDeleteSuccess: 'Category removed successfully',
    side_customRenameSuccess: 'Category title changed to',
    side_hideEmpty: 'Hide Empty Categories',
    side_showEmpty: 'Show Empty Categories',
    side_hideCounts: 'Hide Item Counts',
    side_showCounts: 'Show Item Counts',
    side_compactMode: 'Use Compact Rail',
    side_defaultMode: 'Use Comfort Rail',
    side_sortAlpha: 'Sort: Title A-Z',
    side_sortCount: 'Sort: Heavy Records First',
    side_sortDefault: 'Sort: User Order Index',
    side_optCompact: 'Use Compact Rail Layout',
    side_optHideEmpty: 'Hide Empty Categories from list',
    side_optHideCounts: 'Hide Item Count Badges',
    side_optHideSums: 'Conceal Fast Text Previews',
    side_sortHeading: 'Category Sorting Mode',
    side_sortManual: 'Manual',
    side_layoutHeading: 'Category Layout Sizing',
    side_layoutList: 'List View',
    side_layoutGrid: 'Grid',
    side_moveUp: 'Move sorting level up',
    side_moveDown: 'Move sorting level down',
    side_renameCatTooltip: 'Rename this customized folder',
    side_deleteCatTooltip: 'Permanently remove category folder',
    side_addNewCatBtn: 'Create New Category',
    side_newCatHeader: 'Category Preferences',
    side_newCatLabelField: 'Category Display Title',
    side_newCatLabelPlc: 'e.g., Secondary Debit, Private Emails...',
    side_newCatSchemaField: 'Data Layout Template',
    side_adviceHeader: 'Security Core Blueprint',
    side_advicePara1: 'This secure credentials keeper runs completely in absolute private sandbox storage on your physical device (Offline-First).',
    side_advicePara2: 'All database payloads are compressed and encoded locally with AES-256 PBKDF2.',

    // Main Workspace list
    main_searchPlc: 'Search credentials...',
    main_compactSummaryMode: 'Show Inline Summaries',
    main_sortRecent: 'Sort: Last Changed',
    main_sortAlpha: 'Sort: A-Z Alphabetical',
    main_noDataFound: 'No credentials match your current search queries.',
    main_noDataInCategory: 'No data stored under this category yet.',
    main_deleteConfirm: 'Do you want to permanently erase this secure data?',
    work_searchPlaceholder: 'Quickly lock in passwords, banking tags or worksheets...',
    work_sortByLabel: 'Sorting:',
    work_sortByRecent: 'Recent',
    work_sortByAlpha: 'A-Z Sort',
    work_viewModeLabel: 'View Style:',
    work_viewGridTooltip: 'Show Elegant Cards (Bento style Grid)',
    work_viewTableTooltip: 'Show Ordered Compact Row Entries',

    // Category dynamic labels
    cat_bank: 'Bank Accounts',
    cat_social: 'Social Communities',
    cat_web: 'Websites & Apps',
    cat_wallet: 'Cryptocurrency Wallets',
    cat_ewallet: 'E-Wallets / Mobile Pay',
    cat_phoneapp: 'Mobile Phone Apps',
    cat_sheet: 'Cloud Spreadsheets',
    cat_note: 'Encrypted Safe Notes',

    // Bank Account fields
    f_bankName: 'Bank Provider / Name',
    f_accountNumber: 'Bank Account Number',
    f_accountHolder: 'Card Holder Name',
    f_pin: 'Security Pin Code',
    f_username: 'Online Banking Identifier',
    f_password: 'Card / Account Password',
    f_branch: 'Authorized Branch',
    f_notes: 'Additional Details',
    f_title: 'Account Custom Label',

    // Social fields
    f_platformName: 'Community Network',

    // Web fields
    f_websiteUrl: 'Portal URL Address',

    // Crypto Wallet
    f_walletName: 'Cryptocurrency Wallet',
    f_walletType: 'Wallet Ecosystem Type',
    f_walletAddress: 'Public Address Key',
    f_recoverySeed: 'Recovery Seed Phrase (12-24 keywords)',
    f_privateKey: 'Private Encryption Key',
    f_wallet_type_exchange: 'Centralized Exchange Account',
    f_wallet_type_dex: 'Hot Software Wallet / Web App',
    f_wallet_type_hw: 'Offline Cold Hardware Device',

    // EWallet fields
    f_ewalletName: 'E-Wallet Identifier',
    f_phoneNumber: 'Mobile Phone Number',
    f_linkedBank: 'Associated Direct Bank',

    // Phoneapp fields
    f_appName: 'Smartphone App Name',
    f_nationalId: 'Government National Citizen ID',
    f_passcode: 'Login Pin Code',

    // Google sheet
    f_sheetColumns: 'Data Columns Count',
    f_sheetRows: 'Safe Rows Count',
    f_integratedGSheet: 'Synchronized Sheet Platform',
    f_privateSync: 'Synchronization Space',
    f_syncTime: 'Last Update Cycle',

    // Secure Note fields
    f_notesContent: 'Vault Encrypted Document Body',

    // Reminder Config
    r_reminderEnabled: 'Enable Periodic Alerter',
    r_reminderType: 'Reminder Frequency',
    r_reminderDate: 'Configured Alert Date',
    r_reminderMsg: 'Context Message Alert',
    r_once: 'Record alert one-time',
    r_yearly: 'Record alert annually',

    // Actions
    a_edit: 'Modify Record',
    a_delete: 'Delete Record',
    a_save: 'Commit Changes',
    a_cancel: 'Dismiss',
    a_copied: 'Copied to Clipboard!',
    a_copy: 'Copy',
    a_addNew: 'Add Record',
    a_search: 'Filter text',
    a_show: 'Reveal',
    a_hide: 'Conceal',
    a_sync: 'Sync Platform',
    a_favoriteHint: 'Mark Starred Account',
    a_settings: 'Locker Configurations',
    a_export_backup: 'Backup Encrypted File (JSON)',
    a_import_backup: 'Restore Backup Database File',
    a_import_choose: 'Select JSON Database file...',
    a_import_success: 'Import parsed successfully!',
    a_generate_pwd: 'Compute safe password key',
    a_open_workspace: 'Maximize Secure Workspace',
    a_workspace_title: 'Confidential Workspace Panel',

    // Settings Panel
    sett_title: 'Backup & Recovery Settings',
    sett_desc: 'All secure codes are encrypted locally in your browser storage (localStorage). We highly recommend exporting JSON backups periodically to protect against browser data deletions.',
    sett_exportHeader: 'Export Credentials Database',
    sett_exportDesc: 'Download your entire encrypted database into a portable JSON document for safe keeping.',
    sett_exportBtn: 'Download Secure Backup File (.json)',
    sett_importHeader: 'Import & Restore Data',
    sett_importWarningLabel: 'Warning',
    sett_importWarningDesc: 'Importing database objects will overwrite all existing credentials saved in this device.',
    sett_importBtn: 'Choose Backup File to Import',

    // Theme selector
    theme_title: 'Premium Theme Settings',
    theme_desc: 'Personalize your cryptographic locker with custom aesthetic colors. Exclusively unlocked for PRO Guard.',
    theme_slate: 'Slate Shield',
    theme_cyberpunk: 'Cyberpunk Neon',
    theme_emerald: 'Emerald Classic',
    theme_darkspace: 'Dark Space',
    theme_unlocked_toast: 'Successfully applied premium aesthetic theme!',
    theme_locked_toast: 'Premium visual themes require active PRO Elite Guard status!',

    // Empty States
    work_emptyTitle: 'Your Locker is Currently Empty',
    work_emptySearch: 'No credentials match your search criteria. Please try a different query.',
    work_emptyDesc: 'There are no items or secure documents saved in this category yet.',
    work_createFirst: 'Initiate Your First Safe Entry',

    // Free vs Pro & Security Audit
    tier_free: 'Free Edition',
    tier_pro: 'PRO Elite Guard',
    tier_upgradeBtn: 'Upgrade to PRO',
    tier_proActive: 'PRO Edition Active',
    tier_proBanner: 'Unlock built-in 2FA TOTP Generators, Cloud Sync and Security Audit reports.',
    tier_upgradeTitle: 'Upgrade to Save Code PRO',
    tier_compareTitle: 'Compare Security Features',
    tier_feature_desc1: 'Unlimited credentials across all your browsers',
    tier_feature_desc2: 'Military-grade local offline AES-GCM encryption',
    tier_feature_desc3: 'Built-in 2FA / TOTP Authenticator generator',
    tier_feature_desc4: 'Full Password Health Center & Vulnerability Audit',
    tier_feature_desc5: 'Automatic Secure Sync with Google Sheets',
    tier_feature_desc6: 'Strict security mode and premium visual themes',
    tier_enterCode: 'Enter PRO Activation Code or Coupon',
    tier_codePlc: 'Type VIP2026 or click Upgrade Free...',
    tier_invalidCode: 'Invalid or expired activation code!',
    tier_successUpgrade: 'Success! You have activated the special PRO Elite Edition!',
    
    // TOTP fields
    totp_secretLabel: '2FA/TOTP Key Secret (Base32)',
    totp_secretPlc: 'e.g. JBSWY3DPEHPK3PXP (from Google/Github 2FA settings)',
    totp_codeLabel: 'Two-Factor verification (2FA)',
    totp_desc: 'Rotates standard 6-digit rolling verification codes every 30 seconds.',
    totp_copied: 'Copied 2FA verification code!',
    launch_openNewTab: 'Open in new tab',
    launch_openIncognito: 'Open in Incognito (Copy & Info)',
    launch_openAndCopyPass: 'Open & copy password',
    launch_copyLink: 'Copy link address',
    launch_incognitoToast: 'Copied link! Press Ctrl+Shift+N (Windows) or Cmd+Shift+N (Mac) to open incognito and paste.',
    
    // Audit Dashboard
    audit_title: 'Locker Health & Password Security Audit',
    audit_score: 'Vault Security Score',
    audit_scoreDesc: 'Higher points are awarded for rich password diversity, robust character counts, and registered 2FA secrets.',
    audit_total: 'Analyzed Accounts',
    audit_weak: 'Weak passwords detected',
    audit_weakDesc: 'Under 8 characters long or containing only basic digits or plain words.',
    audit_reused: 'Reused passwords',
    audit_reusedDesc: 'These identical passwords are shared across multiple websites, which increases your cascade breach risk.',
    audit_no2fa: 'Missing 2-Factor Secrets',
    audit_no2faDesc: 'Accounts lacking 2FA records. Turn on 2FA for maximum protection.',
    audit_leaked: 'Breached / Extreme risk',
    audit_leakedDesc: 'Common combinations from history leaks or super obvious sequences (123456, admin, password).',
    audit_perfect: 'Congratulations! Your vault is completely secure with a perfect score!',
    audit_listWeak: 'Low-security passwords (Needs critical updates)',
    audit_listReused: 'Duplicated credentials',
    audit_listNo2fa: 'Vulnerable without active 2FA',
    audit_statusSafe: 'Optimal Security',
    audit_statusWarning: 'Advisory Note',
    audit_statusCritical: 'Urgent Action Required',
  }
};
